/* eslint-disable no-console */

import { execSync } from 'node:child_process';
import fs from 'node:fs/promises';
import path from 'node:path';
import OpenAI from 'openai';

const YEAR = 1404;
const OPENAI_API_KEY = process.env['OPENAI_API_KEY'];
const OPENAI_BASE_URL = process.env['OPENAI_BASE_URL'];

if (!OPENAI_API_KEY) {
  console.error('Please set the OPENAI_API_KEY environment variable.');
  process.exit(1);
}

const openai = new OpenAI({
  apiKey: OPENAI_API_KEY,
  baseURL: OPENAI_BASE_URL,
});

async function fetchEvents(month: number) {
  const url = `https://api.time.ir/v1/event/fa/events/calendar?year=${YEAR}&month=${month}&day=0&base1=0&base2=1&base3=2`;
  const response = await fetch(url, {
    headers: {
      'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:147.0) Gecko/20100101 Firefox/147.0',
      Accept: 'application/json, text/plain, */*',
      'Accept-Language': 'en-US,en;q=0.9',
      'x-api-key': 'ZAVdqwuySASubByCed5KYuYMzb9uB2f7',
      'Sec-GPC': '1',
      'Sec-Fetch-Dest': 'empty',
      'Sec-Fetch-Mode': 'cors',
      'Sec-Fetch-Site': 'same-site',
    },
    referrer: 'https://www.time.ir/',
    method: 'GET',
    mode: 'cors',
  });

  if (!response.ok) {
    throw new Error(`Failed to fetch events for month ${month}: ${response.statusText}`);
  }

  const json = await response.json();
  return json.data.event_list;
}

async function translateEvents(events: any[]) {
  const titles = events.map((e) => e.title);
  const prompt = `Translate the following Iranian calendar event titles from Persian to English.
Return a JSON object with a "translations" key containing an array of strings in the same order.
Do not include any Markdown formatting or code blocks in your response.

Titles to translate:
${JSON.stringify(titles, null, 2)}`;

  const response = await openai.chat.completions.create({
    model: 'gpt-4o-mini',
    messages: [
      {
        role: 'system',
        content:
          'You are a professional translator specializing in Persian to English calendar events. You always respond with pure JSON.',
      },
      { role: 'user', content: prompt },
    ],
    response_format: { type: 'json_object' },
  });

  const content = response.choices[0].message.content;
  if (!content) {
    console.error('OpenAI response:', JSON.stringify(response, null, 2));
    throw new Error('No content from OpenAI');
  }

  try {
    // Attempt to strip markdown code blocks if present
    const cleanContent = content.replace(/^```json\n?|```$/g, '').trim();
    const result = JSON.parse(cleanContent);
    const translatedTitles =
      result.translations || (Array.isArray(result) ? result : Object.values(result)[0]);

    if (!Array.isArray(translatedTitles) || translatedTitles.length !== events.length) {
      console.error('Unexpected JSON structure:', content);
      throw new Error(
        `Translation length mismatch: expected ${events.length}, got ${translatedTitles?.length}`
      );
    }

    return events.map((event, i) => ({
      ...event,
      title_en: translatedTitles[i],
    }));
  } catch (error) {
    console.error('Failed to parse OpenAI response.');
    console.error('Raw content:', content);
    throw error;
  }
}

async function main() {
  console.log(`Fetching events for Jalaali year ${YEAR}...`);
  const allEventsMap = new Map();

  for (let month = 1; month <= 12; month++) {
    console.log(`Fetching month ${month}...`);
    const events = await fetchEvents(month);
    for (const event of events) {
      allEventsMap.set(event.id, event);
    }
  }

  const allEvents = Array.from(allEventsMap.values());
  console.log(`Found ${allEvents.length} unique events. Translating...`);

  const batchSize = 50;
  const translatedEvents = [];

  for (let i = 0; i < allEvents.length; i += batchSize) {
    const batch = allEvents.slice(i, i + batchSize);
    console.log(`Translating batch ${i / batchSize + 1}...`);
    const translatedBatch = await translateEvents(batch);
    translatedEvents.push(...translatedBatch);
  }

  const eventsCode = translatedEvents
    .map((e) => {
      const title = e.title_en.replace(/'/g, "\\'");
      return `  { month: ${e.jalali_month}, day: ${e.jalali_day}, title: '${title}', is_holiday: ${e.is_holiday} },`;
    })
    .join('\n');

  const content = `
/**
 * @file This file is auto-generated by scripts/fetch-events.ts
 * Do not edit this file manually.
 */

/**
 * Represents a single calendar event.
 */
export interface CalendarEvent {
  /** Jalaali month (1-12) */
  month: number;
  /** Jalaali day (1-31) */
  day: number;
  /** Translated title of the event */
  title: string;
  /** Whether the event is a public holiday in Iran */
  is_holiday: boolean;
}

/**
 * A comprehensive list of Jalaali calendar events and holidays.
 * This list is fetched and translated for the Jalaali year ${YEAR}.
 */
// prettier-ignore
export const CALENDAR_EVENTS: CalendarEvent[] = [
${eventsCode}
];
  `.trim();

  const outputPath = path.resolve(process.cwd(), 'src/events.ts');
  await fs.writeFile(outputPath, content);

  console.log('Formatting with Prettier...');
  execSync(`pnpm prettier --write ${outputPath}`);

  console.log(`Done! Saved and formatted ${outputPath}`);
}

main().catch(console.error);
